<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["arreglos", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create arreglos
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "arreglos/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFunctionName" class="col-sm-2 control-label">Function Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["function_name", [], "class" => "form-control", "id" => "fieldFunctionName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFunctionDescription" class="col-sm-2 control-label">Function Of Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["function_description", [], "class" => "form-control", "id" => "fieldFunctionDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFunctionVersion" class="col-sm-2 control-label">Function Of Version</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["function_version", [], "class" => "form-control", "id" => "fieldFunctionVersion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFunctionCode" class="col-sm-2 control-label">Function Of Code</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["function_code", [], "class" => "form-control", "id" => "fieldFunctionCode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFlagDatos" class="col-sm-2 control-label">Flag Of Datos</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["flag_datos", "type" => "number", "class" => "form-control", "id" => "fieldFlagDatos"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGetDatos" class="col-sm-2 control-label">Get Of Datos</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["get_datos", [], "class" => "form-control", "id" => "fieldGetDatos"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIncludeExec" class="col-sm-2 control-label">Include Of Exec</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["include_exec", [], "class" => "form-control", "id" => "fieldIncludeExec"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
