<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["arreglos/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["arreglos/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Function Of Name</th>
            <th>Function Of Description</th>
            <th>Function Of Version</th>
            <th>Function Of Code</th>
            <th>Flag Of Datos</th>
            <th>Get Of Datos</th>
            <th>Include Of Exec</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $arreglo): ?>
            <tr>
                <td><?php echo $arreglo->id ?></td>
            <td><?php echo $arreglo->function_name ?></td>
            <td><?php echo $arreglo->function_description ?></td>
            <td><?php echo $arreglo->function_version ?></td>
            <td><?php echo $arreglo->function_code ?></td>
            <td><?php echo $arreglo->flag_datos ?></td>
            <td><?php echo $arreglo->get_datos ?></td>
            <td><?php echo $arreglo->include_exec ?></td>

                <td><?php echo $this->tag->linkTo(["arreglos/edit/" . $arreglo->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["arreglos/delete/" . $arreglo->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("arreglos/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("arreglos/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("arreglos/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("arreglos/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
